Ghost/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ghost.Domain;
using Ghost.Data.Repositories;
using Ghost.Domain.ViewModel;
using Ghost.Service.Interfaces;
using System.Web.Security;
using System.Drawing;
using System.IO;
using System.Web.UI;

namespace Ghost.Controllers
{
    public class ProfileController : Controller
    {

        private readonly ISecutiryService _securityService;
        private readonly IUserService _userSerivce;
        private readonly IImageService _imageService;
        private readonly IGenderRepository _genderRepository;

        public ProfileController(ISecutiryService securityService,
            IGenderRepository genderRepository,
            IUserService userService, 
            IImageService imageService)
        {
            this._securityService = securityService;
            this._genderRepository = genderRepository;
            this._userSerivce = userService;
            this._imageService = imageService;
        }

        [HttpGet]
        [Authorize]
        public ActionResult Index()
        {
            var user = _securityService.GetUserById(Int32.Parse(User.Identity.Name));
            var viewModel = new ProfileViewModel()
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                AvatarUrl = user.AvatarURL,
                BirthDay = user.BirthDay,
                PhoneNumber = user.PhoneNumber,
                AboutMe = user.AboutMe,
                DateCreated = user.DateCreated,
                DateLastLogin = user.DateLastLogin,
                FileCounter = user.Files.Count,
            };
            if (user.Storage != null)
            {
                viewModel.StorageCounter = 1;
                viewModel.StorageData = new SmallStorageData()
                {
                    TotalSize = user.Storage.MaxSize,
                    CurentSize = user.Storage.CurrentSize,
                    FreeSize = user.Storage.MaxSize - user.Storage.CurrentSize
                };
            }
            else
            {
                viewModel.StorageCounter = 0;
                viewModel.StorageData = null;
            }

            ViewBag.GenderID = new List<Gender>(_genderRepository.GetAll().Where(x=>x.GenderID<3));
            ViewData["PersonID"] = user.UserId.ToString();
            return View(viewModel);
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditSecuritySetting(ProfileViewModel model)
        {
            int changeIndex = 0;

            var user = _securityService.GetUserById(Int32.Parse(User.Identity.Name));
            try
            {
                if((model.NewPassword!=null)&&(model.ConfirmNewPassword!=null))
                if((model.NewPassword.Replace(" ","") == "")||(model.ConfirmNewPassword.Replace(" ","") == ""))
                    throw new System.ArgumentNullException();
            }
            catch (ArgumentException argEx)
            {
                TempData["errorMessage"] = "При изменении пароля, не указан старый пароль. Пароль не был изменен.";
                return RedirectToAction("Index");
            }

            if ((model.OldPassword != null) && (model.NewPassword.Equals(model.ConfirmNewPassword)))
            {
                if (_securityService.ValidateUser(user.Email, CreatePasswordHash(model.OldPassword, user.Salt)))
                {
                    user.Password = CreatePasswordHash(model.NewPassword, user.Salt);
                    changeIndex += 4;
                }
                else
                {
                    TempData["errorMessage"] = "При изменении пароля, указан не верный старый пароль. Пароль не был изменен.";
                }
            }

            if (model.PhoneNumber != null)
            {
                user.PhoneNumber = model.PhoneNumber;
                changeIndex += 1;
            }
            if (model.Email != null)
            { 
                user.Email = model.Email;
                changeIndex += 2;
            }

            switch (changeIndex)
            {
                case 0:
                    break;
                case 1:
                    _securityService.UpdateUser(user);
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                    _securityService.UpdateUser(user);
                    return RedirectToAction("SignOut","Account");
                 default:
                        break;
                }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        public ActionResult EditProfileSetting(ProfileViewModel model,HttpPostedFileBase fileUpload)
        {
            var user = _securityService.GetUserById(Int32.Parse(User.Identity.Name));
            if (model.FirstName != null)
                user.FirstName = model.FirstName;

            if (model.LastName != null)
                user.LastName = model.LastName;

            DateTime nullDate = new DateTime(1, 1, 1, 0, 0, 0);
            if (model.BirthDay != nullDate)
                user.BirthDay = model.BirthDay;

            if (model.AboutMe != null)
                user.AboutMe = model.AboutMe;

            if (model.GenderID != null)
            {
                _userSerivce.AssignGender(user.UserId, model.GenderID);
            }

            if (fileUpload != null)
            {
                //обработка аватара
                Image src = Image.FromStream(fileUpload.InputStream, true, true);
                Image srcThumb = src;
                src = _imageService.ScaleImage(src, 200);
                srcThumb = _imageService.ScaleImage(srcThumb, 30);
                string avatarPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory + "App_Data/" + user.UserId + "/");
                string avatarName;

                user.AvatarURL = avatarPath;
                if (!(Directory.Exists(avatarPath)))
                    Directory.CreateDirectory(avatarPath);

                avatarName = String.Concat("m_",user.UserId.ToString(), ".png");
                src.Save(Path.Combine(avatarPath, avatarName), System.Drawing.Imaging.ImageFormat.Png);
                
                avatarName = String.Concat("s_",user.UserId.ToString(), ".png");
                srcThumb.Save(Path.Combine(avatarPath, avatarName), System.Drawing.Imaging.ImageFormat.Png);

            }

            _securityService.UpdateUser(user);

            return RedirectToAction("Index");
        }

        private static string CreatePasswordHash(string pwd, string salt)
        {
            return FormsAuthentication.HashPasswordForStoringInConfigFile(String.Concat(pwd, salt), "md5");
        }

        [HttpGet]
        [Authorize]
        public ActionResult GetImage(int id, string size)
        {
            var user = _securityService.GetUserById(id);

            string fileName = String.Concat(size, "_", id.ToString(), ".png");
            string path = Path.Combine(user.AvatarURL,fileName );

            return base.File(path, "image/png");
        }
    }
}

Ghost/Controllers/PromoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ghost.Controllers
{
    public class PromoController : Controller
    {
        //
        // GET: /Promo/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Ghost/Controllers/StaticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ghost.Domain;
using Ghost.Domain.ViewModel;
using Ghost.Service.Interfaces;

namespace Ghost.Controllers
{
    public class StaticController : Controller
    {
        private readonly ISecutiryService _securityService;

        public StaticController(ISecutiryService securityService)
        {
            this._securityService = securityService;
        }

        [HttpGet]
        [Authorize]
        public ActionResult Contact()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult AboutUs()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult _LogOnPartial()
        {
            var user = _securityService.GetUserById(Int32.Parse(User.Identity.Name));
            LayoutViewModel userInfo = new LayoutViewModel();
            userInfo.FitstAndLastName = String.Concat(user.FirstName," ",user.LastName);
            userInfo.LastLogOn = user.DateLastLogin.ToString();
            userInfo.AvatarURL = user.AvatarURL;

            return PartialView("_LogOnPartial",userInfo);
        }
    }
}

Ghost/Views/Shared/_FilesListPartial.cshtml
@model Ghost.Domain.ViewModel.PartialFilesListViewModel

<table class="table table-hover table-nomargin">
    <thead>
        <tr>
            <th>Имя файла</th>
            <th>Размер файла, Mб</th>
            <th>Скрыт</th>
            <th style="width: 100px;"></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.Files)
        { 
            <tr>
                <td>@item.FileFullName</td>
                <td>@item.FileSize</td>
                <td>@item.UploadDate</td>
                <td>
                    <a href="@Url.Action("DownloadFile", "Storage", new { id = item.FilesID })" class="btn btn-success" rel="tooltip" title="Извлечь файл"><i class="icon-cloud-download"></i></a>
                </td>

            </tr>
        }

    </tbody>
</table>

Ghost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/Content/Dashboard/css/bootstrap.min.css" />
    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/PagedList.css" />
    <!-- Bootstrap responsive -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/bootstrap-responsive.min.css">
    <!-- jQuery UI -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/plugins/jquery-ui/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="~/Content/Dashboard/css/plugins/jquery-ui/smoothness/jquery.ui.theme.css">
    <!-- PageGuide -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/plugins/pageguide/pageguide.css">
    <!-- Fullcalendar -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/plugins/fullcalendar/fullcalendar.css">
    <link rel="stylesheet" href="~/Content/Dashboard/css/plugins/fullcalendar/fullcalendar.print.css" media="print">
    <!-- chosen -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/plugins/chosen/chosen.css">
    <!-- select2 -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/plugins/select2/select2.css">
    <!-- Datepicker -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/plugins/datepicker/datepicker.css">
    <!-- icheck -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/plugins/icheck/all.css">
    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/style.css">
    <!-- Color CSS -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/themes.css">
    <!-- XEditable -->
	<link rel="stylesheet" href="~/Content/Dashboard/css/plugins/xeditable/bootstrap-editable.css">
    <!--Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Roboto:100,300,500,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>


    <!-- jQuery -->
    <script src="~/Content/Dashboard/js/jquery.min.js"></script>


    <!-- Nice Scroll -->
    <script src="~/Content/Dashboard/js/plugins/nicescroll/jquery.nicescroll.min.js"></script>
    <!-- jQuery UI -->
    <script src="~/Content/Dashboard/js/plugins/jquery-ui/jquery.ui.core.min.js"></script>
    <script src="~/Content/Dashboard/js/plugins/jquery-ui/jquery.ui.widget.min.js"></script>
    <script src="~/Content/Dashboard/js/plugins/jquery-ui/jquery.ui.mouse.min.js"></script>
    <script src="~/Content/Dashboard/js/plugins/jquery-ui/jquery.ui.draggable.min.js"></script>
    <script src="~/Content/Dashboard/js/plugins/jquery-ui/jquery.ui.resizable.min.js"></script>
    <script src="~/Content/Dashboard/js/plugins/jquery-ui/jquery.ui.sortable.min.js"></script>
    <!-- Touch enable for jquery UI -->
    <script src="~/Content/Dashboard/js/plugins/touch-punch/jquery.touch-punch.min.js"></script>
    <!-- slimScroll -->
    <script src="~/Content/Dashboard/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/Dashboard/js/bootstrap.min.js"></script>
    <!-- XEditable -->
	<script src="~/Content/Dashboard/js/plugins/momentjs/jquery.moment.js"></script>
	<script src="~/Content/Dashboard/js/plugins/mockjax/jquery.mockjax.js"></script>
	<script src="~/Content/Dashboard/js/plugins/xeditable/bootstrap-editable.min.js"></script>
	<script src="~/Content/Dashboard/js/plugins/xeditable/demo.js"></script>
	<script src="~/Content/Dashboard/js/plugins/xeditable/address.js"></script>
    <!-- vmap -->
    <script src="~/Content/Dashboard/js/plugins/vmap/jquery.vmap.min.js"></script>
    <script src="~/Content/Dashboard/js/plugins/vmap/jquery.vmap.world.js"></script>
    <script src="~/Content/Dashboard/js/plugins/vmap/jquery.vmap.sampledata.js"></script>
    <!-- Bootbox -->
    <script src="~/Content/Dashboard/js/plugins/bootbox/jquery.bootbox.js"></script>
    <!-- Flot -->
    <script src="~/Content/Dashboard/js/plugins/flot/jquery.flot.min.js"></script>
    <script src="~/Content/Dashboard/js/plugins/flot/jquery.flot.bar.order.min.js"></script>
    <script src="~/Content/Dashboard/js/plugins/flot/jquery.flot.pie.min.js"></script>
    <script src="~/Content/Dashboard/js/plugins/flot/jquery.flot.resize.min.js"></script>
    <!-- Bootbox -->
	<script src="~/Content/Dashboard/js/plugins/bootbox/jquery.bootbox.js"></script>
    <!-- imagesLoaded -->
    <script src="~/Content/Dashboard/js/plugins/imagesLoaded/jquery.imagesloaded.min.js"></script>
    <!-- PageGuide -->
    <script src="~/Content/Dashboard/js/plugins/pageguide/jquery.pageguide.js"></script>
    <!-- FullCalendar -->
    <script src="~/Content/Dashboard/js/plugins/fullcalendar/fullcalendar.min.js"></script>
    <!-- Masked inputs -->
    <script src="~/Content/Dashboard/js/plugins/maskedinput/jquery.maskedinput.min.js"></script>
    <!-- Chosen -->
    <script src="~/Content/Dashboard/js/plugins/chosen/chosen.jquery.min.js"></script>
    <!-- Datepicker -->
    <script src="~/Content/Dashboard/js/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- select2 -->
    <script src="~/Content/Dashboard/js/plugins/select2/select2.min.js"></script>
    <!-- icheck -->
    <script src="~/Content/Dashboard/js/plugins/icheck/jquery.icheck.min.js"></script>
    <!-- Custom file upload -->
    <script src="~/Content/Dashboard/js/plugins/fileupload/bootstrap-fileupload.min.js"></script>
    <script src="~/Content/Dashboard/js/plugins/mockjax/jquery.mockjax.js"></script>

    <!-- Theme framework -->
    <script src="~/Content/Dashboard/js/eakroko.min.js"></script>
    <!-- Theme scripts -->
    <script src="~/Content/Dashboard/js/application.min.js"></script>
    <!-- Just for demonstration -->
    <script src="~/Content/Dashboard/js/demonstration.min.js"></script>

    <link rel="shortcut icon" href="~/Content/Dashboard/img/favicon.ico" />
    <link rel="apple-touch-icon-precomposed" href="~/Content/Dashboard/img/logo.png" />
    <style>
        body { font-family: 'Roboto', sans-serif; font-weight: 300; }
    </style>
</head>
<body data-layout-topbar="fixed">
    <div id="navigation" class="navbar-fixed-top">
        <div class="container-fluid" style="height: 40px;">
            <a href="@Url.Action("Index", "Profile")" id="brand">GHOST</a>
            <ul class="main-nav">
                <!--Навигация-->
                <li>
                    <a href="#" style="padding: 4px 15px;">
                        <span>Панель управления</span>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="dropdown" class='dropdown-toggle' style="padding: 4px 15px;">
                        <span>Хранилище <i class="caret"></i></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Галерея</a>
                        </li>
                        <li>
                            <a href="@Url.Action("FilesList", "Storage")">Файлы</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Storage")">Настройка</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <div class="user">
                @Html.Action("_LogOnPartial", "Static")
            </div>
        </div>
    </div>

    <div class="container-fluid" id="content">
        <div id="main">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>

    <div id="footer">
        <p>
            Ghost. All right reserved (c) 2014
                <span class="font-grey-4">|</span>
            <a href="@Url.Action("Contact", "Static")">Контакты</a>
            <span class="font-grey-4">|</span>
            <a href="@Url.Action("AboutUs", "Static")">О нас</a>
        </p>
        <a href="#" class="gototop"><i class="icon-arrow-up"></i></a>
    </div>
</body>
</html>

Ghost/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>@ViewBag.Title</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/bootstrap.min.css">
    <!-- Bootstrap responsive -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/bootstrap-responsive.min.css">
    <!-- icheck -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/plugins/icheck/all.css">
    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/style.css">
    <!-- Color CSS -->
    <link rel="stylesheet" href="~/Content/Dashboard/css/themes.css">
    <!--Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Roboto:100,300,500,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>


    <!-- jQuery -->
    <script src="~/Content/Dashboard/js/jquery.min.js"></script>

    <!-- Nice Scroll -->
    <script src="~/Content/Dashboard/js/plugins/nicescroll/jquery.nicescroll.min.js"></script>
    <!-- Validation -->
    <script src="~/Content/Dashboard/js/plugins/validation/jquery.validate.min.js"></script>
    <script src="~/Content/Dashboard/js/plugins/validation/additional-methods.min.js"></script>
    <!-- icheck -->
    <script src="~/Content/Dashboard/js/plugins/icheck/jquery.icheck.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/Dashboard/js/bootstrap.min.js"></script>
    <script src="~/Content/Dashboard/js/eakroko.js"></script>


    <link rel="shortcut icon" href="~/Content/Dashboard/img/favicon.ico" />
    <link rel="apple-touch-icon-precomposed" href="~/Content/Dashboard/img/logo.png" />

    <style>
    body {
        font-family: 'Roboto', sans-serif;
        font-weight:300;
    }
</style>
</head>
<body>
    <body class="login">
        <div class="wrapper">
            <h1><a href="@Url.Action("Index", "Promo")">
                <img src="~/Content/Dashboard/img/logo.png" alt="" class="retina-ready" width="59" height="49" />Ghost</a></h1>
            <div class="login-body">
                @RenderBody()
            </div>
        </div>

    </body>
</body>
</html>

Ghost/Views/Shared/_LogOnPartial.cshtml
@model Ghost.Domain.ViewModel.LayoutViewModel
<style>
    li span { width: auto; padding: 6px 15px; display: block; font-weight: normal; white-space: nowrap; }
</style>
<div class="dropdown" style="height: 40px;">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="height: 67.5%;">
        @{
            if (Model.FitstAndLastName.Trim().IsEmpty())
            {
            <i class="icon-reorder"></i>
            }
            else
            {
            <text>@Html.DisplayFor(model => model.FitstAndLastName)</text>
            }
        }
        @{
            if (Model.AvatarURL == null)
            {
                <img src="~/Content/Dashboard/img/avatar.jpg" />
            }
            else
            {
                <img src="@Url.Action("GetImage", "Profile", new { id = Int32.Parse(User.Identity.Name), size = "s" })" alt="" />
            }
        }
        <!--<img src="~/Content/Dashboard/img/avatar.png" alt="" />-->
    </a>
    <ul class="dropdown-menu pull-right" style="font-weight: 100">
        <li style="background-color: #1B67AF; color: #FFFFFF">
            <span>Последний вход: @Html.DisplayFor(model => model.LastLogOn)</span>
        </li>
        <li>
            <a href="@Url.Action("Index", "Profile")">Профиль</a>
        </li>
        <li>
            <a href="@Url.Action("SignOut", "Account")">Выход</a>
        </li>
    </ul>
</div>